//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARMDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutovauxContext : DbContext
    {
        public AutovauxContext()
            : base("name=AutovauxContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bron> Bron { get; set; }
        public virtual DbSet<Bus_fleet> Bus_fleet { get; set; }
        public virtual DbSet<Bus_types> Bus_types { get; set; }
        public virtual DbSet<Carriers> Carriers { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<Rate_plans> Rate_plans { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<Schemas> Schemas { get; set; }
        public virtual DbSet<TimetableList> TimetableList { get; set; }
        public virtual DbSet<Timetables> Timetables { get; set; }
        public virtual DbSet<TimetableTemp> TimetableTemp { get; set; }
        public virtual DbSet<GenialView> GenialView { get; set; }
    }
}
