//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARMDatabase
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Bron
    {
        public int ID_BRON { get; set; }
        public System.DateTime DATE { get; set; }
        public int BUS { get; set; }
        public System.DateTime DEPART_TIME { get; set; }
        public string ONTOUR { get; set; }
        public int COUNT { get; set; }
    }
}
