//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARMDatabase
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Bus_fleet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bus_fleet()
        {
            this.Routes = new ObservableCollection<Routes>();
        }
    
        public int BUS_ID { get; set; }
        public string REG_ID { get; set; }
        public int ORG_ID_FK { get; set; }
        public int BUS_TYPE_ID_FK { get; set; }
        public int SCHEME_ID_FK { get; set; }
    
        public virtual Bus_types Bus_types { get; set; }
        public virtual Carriers Carriers { get; set; }
        public virtual Schemas Schemas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Routes> Routes { get; set; }
    }
}
