//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARMDatabase
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Profiles
    {
        public int PROFILE_ID { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public string MNAME { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string HASH_PASSWORD { get; set; }
        public string SALT { get; set; }
        public bool PROFILE_STATE { get; set; }
        public int ROLE_ID_FK { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
